#ifndef AUTONOMI_H
#define AUTONOMI_H

/* Warning: This file is auto-generated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes for FFI operations
 */
typedef enum ErrorCode {
  Success = 0,
  InvalidArgument = 1,
  ConnectionError = 2,
  RuntimeError = 3,
  InvalidUtf8 = 4,
  NullPointer = 5,
} ErrorCode;

/**
 * Opaque type for the Client
 */
typedef struct FfiClient FfiClient;

/**
 * Opaque type for the Wallet
 */
typedef struct FfiWallet FfiWallet;

/**
 * Result structure for FFI operations
 */
typedef struct FfiResult {
  enum ErrorCode error_code;
  char *error_message;
} FfiResult;

/**
 * Initialize a client connected to the local network
 * Returns a pointer to the client or null on error
 */
struct FfiClient *autonomi_client_init_local(struct FfiResult *result);

/**
 * Initialize a client connected to the main network
 */
struct FfiClient *autonomi_client_init(struct FfiResult *result);

/**
 * Free a client instance
 */
void autonomi_client_free(struct FfiClient *client);

/**
 * Upload data and return the address as a hex string
 */
char *autonomi_client_data_put(struct FfiClient *client,
                               const uint8_t *data,
                               uintptr_t data_len,
                               struct FfiWallet *wallet,
                               struct FfiResult *result);

/**
 * Get data from the network using a hex address
 */
uint8_t *autonomi_client_data_get(struct FfiClient *client,
                                  const char *address_hex,
                                  struct FfiResult *result,
                                  uintptr_t *data_len);

/**
 * Create a wallet from a private key for local network
 */
struct FfiWallet *autonomi_wallet_from_private_key_local(const char *private_key,
                                                         struct FfiResult *result);

/**
 * Free a wallet instance
 */
void autonomi_wallet_free(struct FfiWallet *wallet);

/**
 * Free a C string allocated by this library
 */
void autonomi_free_string(char *s);

/**
 * Free data allocated by this library
 */
void autonomi_free_data(uint8_t *data, uintptr_t len);

#endif  /* AUTONOMI_H */
