use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_path = PathBuf::from(&crate_dir).join("autonomi.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        autogen_warning: Some("/* Warning: This file is auto-generated by cbindgen. Don't modify manually. */".to_string()),
        include_guard: Some("AUTONOMI_H".to_string()),
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_path);
}