[package]
name = "autonomi-uniffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "autonomi_uniffi"

[[bin]]
name = "uniffi-bindgen"
path = "bindgen.rs"

[[bin]]
name = "uniffi-bindgen-swift"
path = "bindgen-swift.rs"

[dependencies]
autonomi = { path = "../autonomi" }
bytes = "1.0.1"
rmp-serde = "1.1.1"
self_encryption = "0.34.0"
thiserror = "1.0"
uniffi = { version = "0.29.4", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.29.4", features = [ "build" ] }

[lints]
workspace = true
